# Module#3 Assignment (NumPy)

### Submitted by : Muhammad Bilal Jamil (mjamil@mail.yu.edu)
### Submitted to : Prof. Topor

###### Q1) :
Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b, your output should contain only one 2 even if array a contains more than one 2 within it.


In [23]:
#importing numpy library

import numpy as np
a =  np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

'''As per the 'Python for Data Analysis' book instructions and table 4-6, the array set operator 'intersect1d(x,y)' computes
all the common elements in 'x' and 'y' '''

dist_output = np.intersect1d(a,b)
print('The unique values are:',dist_output)

The unique values are: [2 4]


###### Q2):
Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value.

In [58]:
#Using the Numpy operator 'arrange' and 'reshape' we will generate an array which has 3 rows and 5 columns:

arr3d = np.arange(1,16).reshape((3, 5))
print('The 3x5 array is:\n', arr3d)

The 3x5 array is:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [114]:
# But the requested output is not actually a 3x5 matrix rather its a 5x3 array with row elements becoming column elements
# Hence, for this we will use NumPy's transposing 'T' method to get an output from 1-15 as desired in question and save
# it in a variable called 'final_arr':

final_arr= arr3d.T
print('The 5x3 array is:\n', final_arr)

The 5x3 array is:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


###### Q3:
You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
. Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [64]:
# since we have used a,b before and we don't want the values to be updated. Then, let's instead create c and d arrays:

c =  np.array([12, 5, 7, 15, 3, 1, 8])
d =  np.array([14, 6, 3, 11, 19, 12, 5])

In [110]:
''' We are using a 'lamda' function, here we are checking which elements of 'c' are 'not in' 'd'. We use the 'filter' 
function to make sure the item is accepted or not. Then we use a 'list' function which helps us convert the accepted outcome 
to a list. Which with the help of 'np.array' we convert into a new array 'c'.   '''

c = np.array(list(filter(lambda x: x not in d, c)))
print('The final result is :',c)

The final result is : [ 7 15  1  8]


###### Q4:
The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

In [124]:
'''In Q2 we created a new variable 'final_arr' which stored the 5x3 array after we transposed it. Now, for this exact problem,
Our strategy will be very simple. We will use the NumPy function 'flatten()' and use it to flatten our original 'final_arr'
array. But we are not done with it because it is not sorted. Hence, we will also use another NumPy function 'sort' to finally
be able to successfully flatten the array'''

flat_arr = np.sort(final_arr.flatten())
print('The flattened array is:\n',flat_arr)

The flattened array is:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


##### Q5:
For this problem you will load a small data set to your online GitHub repository and then read it into a NumPy 2D array. You will then use the content that NumPy array to answer a series of analytical questions. Using the nyc_water array you’ve created, answer the following questions using NumPy’s slicing, methods, and functions:

1. What is the maximum yearly NYC consumption of water in millions of gallons per day?
2. How many calendar years are represented within this data set? NumPy's shape command is one way to find out.
3. What is the mean and the standard deviation of the per capita daily water consumption?
4. What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [128]:
# Prework for Q5:

import pandas as pd

# suppress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pd.read_csv('https://raw.githubusercontent.com/mbjamil92/DAV-5400/master/Water_Consumption_In_The_New_York_City.csv').to_numpy()
                            
# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

In [129]:
# Checking dataset :
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

In [167]:
# Solving Part (1) of Q5:
# Since, reading the data set the column to be used is 3rd one i.e. 'NYC Consumption(Million gallons per day)' which will be 
# '2' starting from 0 and saving that value in the variable 'max_value'. Also, using the NumPy 'max' function to find the value:

max_value = np.max(nyc_water[0:,2])
print('The maximum yearly NYC consumption of water in millions of Gallons per day is:\n', max_value)

The maximum yearly NYC consumption of water in millions of Gallons per day is:
 1512.0


In [148]:
# Solving Part (2) of Q5:
# Since, we know the 'Year' column is 1st hence, the we will use the range '0:,0' for this. Now using the NumPy 'count_nonzero'
# function to count all the years from 1979 to 2019.

count_years = np.count_nonzero(nyc_water[0:,0])
print('The total number of calendar years are:\n',count_years)

The total number of calendar years are:
 41


In [168]:
# Solving Part (3) of Q5:
# From analyzing the dataset, we know that the column of our interest is '3' which can be accessed by the range '0:,3'
# storing this value in the variable 'per_capita'. Using, NumPy's np.std function to find Standard Deviation
# storing the this value in the variable 'std_capita':

per_capita = nyc_water[0:,3]
std_capita = np.std(per_capita)
print('The standard deviation of the per capita daily water consumption in Gallons is:\n', std_capita)

# Now, we have found the standard deviation, let's find the mean. Using NumPy's np.mean function to find 'Mean' and 
# storing this in the variable 'mean_capita':

mean_capita = np.mean(per_capita)
print('\nThe mean of the per capita daily water consumption in Gallons is:\n', mean_capita)

The standard deviation of the per capita daily water consumption in Gallons is:
 31.847177467886052

The mean of the per capita daily water consumption in Gallons is:
 158.41463414634146


In [172]:
# Solving Part (4) of Q5:

# Here we are using NumPy's np.diff function to apply on the 2nd column. We will find 2nd column by using the range ':,1'
# We store that information as requested in the variable 'pop_diff':

pop_diff = np.diff(nyc_water[:,1])
print('The difference is:\n', pop_diff)

The difference is:
 [-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  97830.
  75069.   50707.   38648.   30794.    7795.  -37705.  -39523.  -61931. ]


## Citations:

* https://numpy.org/doc/stable/reference/generated/numpy.vstack.html#numpy.vstack
* https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange
* https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full
* https://numpy.org/doc/stable/reference/generated/numpy.searchsorted.html
* https://www.guru99.com/python-lambda-function.html
* https://www.askpython.com/python/examples/in-and-not-in-operators-in-python
* https://numpy.org/doc/stable/reference/generated/numpy.sort.html
* https://numpy.org/doc/stable/user/basics.rec.html?highlight=flatten#numpy.lib.recfunctions.flatten_descr
* https://numpy.org/doc/stable/reference/generated/numpy.std.html
* https://numpy.org/doc/stable/reference/generated/numpy.mean.html?highlight=numpy%20mean#numpy.mean
* https://numpy.org/doc/stable/reference/generated/numpy.diff.html?highlight=diff#numpy.diff